### ISSUE TITLE
Update the comment to show risks & changes

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/ovm-cli#97] opened 2023-10-19 10:14 UTC
Now that change have a new shape, we can improve the comment that we post.

## Add Terraform plan information

Since we are capturing this, we should post this as the expected changes, this should remove the need for the Terraform plan in a separate comment.

## Add risks

Now that we have risks, we need to be able to format these in the comment too

**Comment by DavidS-om** [comment] 2023-11-08 09:10
Duplicate of #110

**Closed by DavidS-om** 2023-11-08 09:10 UTC
