### ISSUE TITLE
Extract ItemDiffs from plans

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/ovm-cli#96] opened 2023-10-19 09:47 UTC
We need to extract an ItemDiff for each changing item in a plan so that it can be sent to the new endpoint here: https://github.com/overmindtech/api-server/issues/423

These should have a default scope like `tf_plan` that will be updated if the server actually finds the item

**Comment by DavidS-om** [comment] 2023-11-08 09:09
Duplicate of #109

**Closed by DavidS-om** 2023-11-08 09:09 UTC
